Version 2.1.6, changed sourcecode archive generation, use NaCl version 20110221, do not duplicate NaCl sourcecode, support iproute2 for persistent tunnel creation on Debian, support running as root on Debian, removed autogenerated header files

diff --git a/debian/static/etc/network/if-pre-up.d/quicktun b/debian/static/etc/network/if-pre-up.d/quicktun
--- a/debian/static/etc/network/if-pre-up.d/quicktun
+++ b/debian/static/etc/network/if-pre-up.d/quicktun
@@ -1,3 +1,15 @@
 #!/bin/sh
 test -n "${IF_QT_REMOTE_ADDRESS}" || exit 0
-/usr/sbin/openvpn --mktun --dev "${IFACE}" --user quicktun
+test -z "${IF_QT_NO_PRECREATE}" || exit 0
+if [ -n "${IF_QT_TUN_MODE}" ]; then
+	DEVTYPE="tun"
+else
+	DEVTYPE="tap"
+fi
+if [ -x /usr/sbin/openvpn ]; then
+	/usr/sbin/openvpn --mktun --dev "${IFACE}" --dev-type "${DEVTYPE}" --user quicktun
+elif [ -x /sbin/ip ]; then
+	/sbin/ip tuntap add dev "${IFACE}" mode "${DEVTYPE}" user quicktun
+else
+	echo "Unable to pre-create tun/tap interface. Run QuickTun as root."
+fi
